name: firstproject
description: Primeiro projeto com o Vaden.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.8.0+1
  shelf_plus: ^1.0.2
  sqlite3: ^2.7.5
  vaden: ^0.0.7

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.0.7